import { TierConfig, LaunchProject, Reward } from "@/types";

export const FAIRSCALE_API_BASE = "https://api.fairscale.xyz";

export const TIER_CONFIGS: Record<string, TierConfig> = {
  bronze: {
    name: "Bronze",
    minScore: 0,
    maxScore: 25,
    color: "#CD7F32",
    bgColor: "bg-gradient-to-br from-amber-900/20 to-amber-800/10",
    borderColor: "border-amber-700/50",
    textColor: "text-amber-400",
    gradientFrom: "from-amber-700",
    gradientTo: "to-amber-500",
    icon: "🥉",
    multiplier: 1.0,
    benefits: [
      "Basic platform access",
      "View launchpad listings",
      "Community chat access",
    ],
  },
  silver: {
    name: "Silver",
    minScore: 25,
    maxScore: 50,
    color: "#C0C0C0",
    bgColor: "bg-gradient-to-br from-gray-400/20 to-gray-300/10",
    borderColor: "border-gray-400/50",
    textColor: "text-gray-300",
    gradientFrom: "from-gray-400",
    gradientTo: "to-gray-200",
    icon: "🥈",
    multiplier: 1.25,
    benefits: [
      "All Bronze benefits",
      "Early access to select launches",
      "1.25x reward multiplier",
      "Priority support",
    ],
  },
  gold: {
    name: "Gold",
    minScore: 50,
    maxScore: 75,
    color: "#FFD700",
    bgColor: "bg-gradient-to-br from-yellow-600/20 to-yellow-500/10",
    borderColor: "border-yellow-500/50",
    textColor: "text-yellow-400",
    gradientFrom: "from-yellow-500",
    gradientTo: "to-yellow-300",
    icon: "🥇",
    multiplier: 1.75,
    benefits: [
      "All Silver benefits",
      "Access to all launches",
      "1.75x reward multiplier",
      "Exclusive airdrops",
      "Governance voting rights",
    ],
  },
  platinum: {
    name: "Platinum",
    minScore: 75,
    maxScore: 100,
    color: "#E5E4E2",
    bgColor: "bg-gradient-to-br from-indigo-500/20 to-purple-500/10",
    borderColor: "border-indigo-400/50",
    textColor: "text-indigo-300",
    gradientFrom: "from-indigo-400",
    gradientTo: "to-purple-400",
    icon: "💎",
    multiplier: 2.5,
    benefits: [
      "All Gold benefits",
      "Guaranteed allocation in all launches",
      "2.5x reward multiplier",
      "VIP airdrops & NFTs",
      "Advisory board access",
      "Custom referral program",
    ],
  },
};

export const MOCK_LAUNCHES: LaunchProject[] = [
  {
    id: "1",
    name: "SolGuard Protocol",
    symbol: "GUARD",
    description:
      "Decentralized insurance protocol for Solana DeFi. Protect your positions against smart contract exploits and market crashes with reputation-weighted coverage pools.",
    logo: "🛡️",
    website: "https://solguard.io",
    twitter: "@solguard",
    minTier: "gold",
    totalRaise: 500000,
    tokenPrice: 0.05,
    totalTokens: 10000000,
    startDate: "2025-02-15T00:00:00Z",
    endDate: "2025-02-22T00:00:00Z",
    status: "active",
    participants: 1247,
    raised: 387500,
    chain: "Solana",
    tags: ["DeFi", "Insurance", "Security"],
  },
  {
    id: "2",
    name: "ReputeDAO",
    symbol: "REPD",
    description:
      "Governance framework that weights voting power by on-chain reputation. Build DAOs where the most trusted members have the strongest voice.",
    logo: "🏛️",
    website: "https://reputedao.xyz",
    twitter: "@reputedao",
    minTier: "silver",
    totalRaise: 300000,
    tokenPrice: 0.02,
    totalTokens: 15000000,
    startDate: "2025-02-20T00:00:00Z",
    endDate: "2025-02-27T00:00:00Z",
    status: "upcoming",
    participants: 0,
    raised: 0,
    chain: "Solana",
    tags: ["DAO", "Governance", "Reputation"],
  },
  {
    id: "3",
    name: "ChainCredit",
    symbol: "CRED",
    description:
      "Under-collateralized lending powered by on-chain reputation scores. Higher FairScore means lower collateral requirements and better interest rates.",
    logo: "💳",
    website: "https://chaincredit.fi",
    twitter: "@chaincredit",
    minTier: "platinum",
    totalRaise: 1000000,
    tokenPrice: 0.10,
    totalTokens: 10000000,
    startDate: "2025-01-10T00:00:00Z",
    endDate: "2025-01-17T00:00:00Z",
    status: "completed",
    participants: 3421,
    raised: 1000000,
    chain: "Solana",
    tags: ["DeFi", "Lending", "Credit"],
  },
  {
    id: "4",
    name: "TrustBridge",
    symbol: "TRBG",
    description:
      "Cross-chain reputation bridge that ports your FairScore across multiple blockchains. One reputation, every chain.",
    logo: "🌉",
    website: "https://trustbridge.xyz",
    twitter: "@trustbridge",
    minTier: "bronze",
    totalRaise: 200000,
    tokenPrice: 0.01,
    totalTokens: 20000000,
    startDate: "2025-03-01T00:00:00Z",
    endDate: "2025-03-08T00:00:00Z",
    status: "upcoming",
    participants: 0,
    raised: 0,
    chain: "Solana",
    tags: ["Infrastructure", "Cross-chain", "Bridge"],
  },
  {
    id: "5",
    name: "FairSwap DEX",
    symbol: "FSWP",
    description:
      "Decentralized exchange with reputation-weighted liquidity pools. Higher reputation LPs earn better fee tiers and reduced impermanent loss protection.",
    logo: "🔄",
    website: "https://fairswap.io",
    twitter: "@fairswap",
    minTier: "silver",
    totalRaise: 750000,
    tokenPrice: 0.075,
    totalTokens: 10000000,
    startDate: "2025-02-25T00:00:00Z",
    endDate: "2025-03-04T00:00:00Z",
    status: "upcoming",
    participants: 0,
    raised: 0,
    chain: "Solana",
    tags: ["DeFi", "DEX", "AMM"],
  },
];

export const MOCK_REWARDS: Reward[] = [
  {
    id: "1",
    title: "Early Adopter Airdrop",
    description:
      "Exclusive token airdrop for early FairGate users with Gold tier or above.",
    type: "airdrop",
    minTier: "gold",
    minScore: 50,
    value: "500 FGATE",
    claimed: false,
    expiresAt: "2025-03-31T00:00:00Z",
    icon: "🪂",
  },
  {
    id: "2",
    title: "Platinum Staking Boost",
    description:
      "2.5x staking reward multiplier for Platinum tier members. Stack your reputation for maximum yield.",
    type: "multiplier",
    minTier: "platinum",
    minScore: 75,
    value: "2.5x Multiplier",
    claimed: false,
    expiresAt: "2025-06-30T00:00:00Z",
    icon: "⚡",
  },
  {
    id: "3",
    title: "VIP Launch Access",
    description:
      "Guaranteed whitelist spot for the next 3 premium launches on FairGate.",
    type: "access",
    minTier: "gold",
    minScore: 60,
    value: "3 Whitelist Spots",
    claimed: false,
    expiresAt: "2025-04-30T00:00:00Z",
    icon: "🎫",
  },
  {
    id: "4",
    title: "Reputation Pioneer NFT",
    description:
      "Limited edition NFT for Silver+ members. Proof of early reputation building on Solana.",
    type: "nft",
    minTier: "silver",
    minScore: 25,
    value: "1 NFT",
    claimed: false,
    expiresAt: "2025-05-31T00:00:00Z",
    icon: "🎨",
  },
  {
    id: "5",
    title: "Bronze Welcome Bonus",
    description:
      "Welcome bonus tokens for all verified FairGate users. Start your reputation journey.",
    type: "airdrop",
    minTier: "bronze",
    minScore: 0,
    value: "100 FGATE",
    claimed: false,
    expiresAt: "2025-12-31T00:00:00Z",
    icon: "🎁",
  },
  {
    id: "6",
    title: "Gold Trading Fee Discount",
    description:
      "50% reduction in platform fees for Gold tier members across all launchpad participations.",
    type: "multiplier",
    minTier: "gold",
    minScore: 55,
    value: "50% Fee Discount",
    claimed: false,
    expiresAt: "2025-06-30T00:00:00Z",
    icon: "💰",
  },
];

export const TIER_ORDER: Record<string, number> = {
  bronze: 0,
  silver: 1,
  gold: 2,
  platinum: 3,
};

export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/dashboard", label: "Dashboard" },
  { href: "/launchpad", label: "Launchpad" },
  { href: "/rewards", label: "Rewards" },
  { href: "/leaderboard", label: "Leaderboard" },
];
